module Zirconia
  class Application
    attr_reader dir: Pathname
    attr_reader name: String

    def initialize: (dir: String, name: String) -> void

    def create!: -> void

    def load!: -> void

    def gem_path: (*String, ?ext: Symbol?) -> Pathname

    def lib_path: (*String, ?ext: Symbol?) -> Pathname

    def path: (*String, ?ext: Symbol?) -> Pathname

    def to_sym: -> Symbol

    attr_reader main_file: Pathname

    private
    
    attr_reader lib_dir: Pathname
    attr_reader gem_dir: Pathname

    def build_path: (*String, dir: Pathname, ext: Symbol?) -> Pathname
  end
end
