class Pathname
  def initialize: (String path) -> void

  def read: -> String

  def write: (String contents) -> void

  def basename: (?String) -> Pathname

  def dirname: -> Pathname

  def exist?: -> bool

  def join: (*String) -> Pathname

  def to_s: -> String
end
